# Generated by Django 2.0.1 on 2018-04-10 16:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, help_text='Enter age :', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('height', models.FloatField(blank=True, help_text='Enter height (In Centimeter) :', null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(20)])),
                ('weight', models.FloatField(blank=True, help_text='Enter weight (In Lbs) :', null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(20)])),
                ('ailments', models.TextField(blank=True, help_text='Enter comma separated list of pre-existing ailments :', max_length=1000, null=True)),
                ('tobacco', models.BooleanField(default=False, help_text='Do you consume tobacco?')),
                ('smoke', models.BooleanField(default=False, help_text='Do you consume smoke?')),
                ('drink', models.BooleanField(default=False, help_text='Do you consume drink?')),
                ('exercise', models.IntegerField(blank=True, choices=[(2, '>15 hours/week'), (1, '6-15 hours/week'), (0, '<6 hours/week')], default=1, help_text='Select how much do you exercise?')),
                ('travel_time', models.IntegerField(blank=True, choices=[(2, '>10 hours/week'), (1, '5-10 hours/week'), (0, '<5 hours/week')], default=1, help_text='Select how much do you travel?')),
                ('sleep_time', models.IntegerField(blank=True, choices=[(2, '>8 hours/day'), (1, '6-8 hours/day'), (0, '<6 hours/day')], default=1, help_text='Select how much do you sleep?')),
                ('job_type', models.TextField(blank=True, help_text='Enter your job description :', max_length=1000, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
