# Generated by Django 2.0.1 on 2018-04-14 01:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='healthcare_costs',
            field=models.FloatField(blank=True, help_text='Enter your total healthcare costs', null=True, validators=[django.core.validators.MaxValueValidator(50000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='height',
            field=models.FloatField(blank=True, help_text='Enter height (In Inches) :', null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
