# Generated by Django 2.0.1 on 2018-04-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20180426_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='sleep_time',
            field=models.IntegerField(choices=[(2, '>8 hours/day'), (1, '6-8 hours/day'), (0, '<6 hours/day')], default=(1, '6-8 hours/day'), help_text='Select how much do you sleep?'),
        ),
    ]
