# Generated by Django 2.0.1 on 2018-04-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_auto_20180426_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='exercise',
            field=models.IntegerField(choices=[(2, '>15 hours/week'), (1, '6-15 hours/week'), (0, '<6 hours/week')], default=1, help_text='Select how much do you exercise?'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='travel_time',
            field=models.IntegerField(choices=[(2, '>10 hours/week'), (1, '5-10 hours/week'), (0, '<5 hours/week')], default=1, help_text='Select how much do you travel?'),
        ),
    ]
